# Generated by Django 4.2.30 on 2026-09-12 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.CharField(db_index=True, editable=False, max_length=20, unique=True)),
                ('citizen_name', models.CharField(max_length=150)),
                ('citizen_phone', models.CharField(max_length=20)),
                ('citizen_email', models.EmailField(blank=True, max_length=254)),
                ('description', models.TextField()),
                ('nlp_tags', models.CharField(blank=True, help_text='Comma-separated keyword tags', max_length=255)),
                ('priority', models.CharField(choices=[('emergency', 'Emergency'), ('high', 'High Priority'), ('standard', 'Standard')], default='standard', max_length=20)),
                ('address_text', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('evidence_photo', models.ImageField(blank=True, null=True, upload_to='complaints/evidence/')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('assigned', 'Auto-Assigned'), ('in_progress', 'Inspection / In-Progress'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('reopened', 'Reopened')], default='submitted', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('head_name', models.CharField(blank=True, max_length=150)),
                ('head_designation', models.CharField(blank=True, max_length=150)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('helpline_number', models.CharField(blank=True, max_length=20)),
                ('emergency_number', models.CharField(blank=True, max_length=20)),
                ('office_address', models.CharField(blank=True, max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='departments/logos/')),
                ('description', models.TextField(blank=True)),
                ('sla_hours', models.PositiveIntegerField(default=72, help_text='Service Level Agreement target, in hours')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=110, unique=True)),
                ('icon', models.CharField(default='folder', help_text="Lucide icon name, e.g. 'droplet', 'zap', 'trash-2'", max_length=50)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('content', models.TextField(help_text='HTML or plain text content, rendered as-is')),
                ('show_in_footer', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(help_text="Official designation, e.g. 'Municipal Commissioner'", max_length=150)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team/photos/')),
                ('bio', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_ribhay_credit', models.BooleanField(default=False, help_text='Tick for RiBhay Studio engineering-credit entries')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to='civiq.department')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OfficerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, max_length=150)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='officers/photos/')),
                ('is_active_officer', models.BooleanField(default=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='officers', to='civiq.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='officer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__first_name'],
            },
        ),
        migrations.AddField(
            model_name='department',
            name='sectors',
            field=models.ManyToManyField(blank=True, related_name='departments', to='civiq.sector'),
        ),
        migrations.CreateModel(
            name='ComplaintTimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('assigned', 'Auto-Assigned'), ('in_progress', 'Inspection / In-Progress'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('reopened', 'Reopened')], max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='civiq.complaint')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplaintResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.TextField()),
                ('proof_image', models.ImageField(upload_to='complaints/resolutions/')),
                ('resolved_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resolution', to='civiq.complaint')),
                ('resolved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolutions', to='civiq.officerprofile')),
            ],
        ),
        migrations.AddField(
            model_name='complaint',
            name='assigned_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_complaints', to='civiq.officerprofile'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='civiq.department'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='sector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='civiq.sector'),
        ),
        migrations.CreateModel(
            name='CitizenFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='civiq.complaint')),
            ],
        ),
    ]
